# Generated by Django 3.0.3 on 2024-05-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='职位要求')),
                ('location', models.CharField(max_length=100, verbose_name='工作地点')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='发布日期')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='薪资')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('status', models.CharField(choices=[('applied', '已申请'), ('interview', '面试中'), ('hired', '已录用'), ('rejected', '已拒绝')], default='applied', max_length=20, verbose_name='申请状态')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job', verbose_name='职位')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
                'ordering': ['id'],
            },
        ),
    ]
