# Generated by Django 3.0.3 on 2024-05-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField(blank=True, verbose_name='教育经历')),
                ('experience', models.TextField(blank=True, verbose_name='工作经历')),
                ('skills', models.TextField(blank=True, verbose_name='技能')),
                ('projects', models.TextField(blank=True, verbose_name='项目经历')),
                ('certifications', models.TextField(blank=True, verbose_name='认证和证书')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='user.Jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['id'],
            },
        ),
    ]
